export const AppRoute = {
  AUTH: 'Auth',
  SIGN_IN: 'SignIn',
  SIGN_UP: 'SignUp',
  RESET_PASSWORD: 'ResetPassrord',
  ROOT: 'Root',
  HOME: 'Home',
  ORDER: 'Order',
  PRODUCT: 'Product',
  SETTING: 'Setting',
  TODO_IN_PROGRESS: 'ToDoInProgress',
  HOME_SCREEN: 'HomeScreen',
  HOME_DETAIL: 'HomeDetail',
  SETTING_SCREEN: 'SettingScreen',
  PRODUCT_SCREEN: 'ProductScreen',
  PRODUCT_DETAIL_SCREEN: 'ProductScreenDetail',
  ORDER_SCREEN: 'OrderScreen',
  ORDER_DETAIL_SCREEN: 'OrderScreenDetail',
}
