
export const counterContants = {
  COUNTER_INCREMEMT: "COUNTER_INCREMEMT",
  COUNTER_DECREMENT: "COUNTER_DECREMENT",
  SET_COUNTER_API: "SET_COUNTER_API",
  SET_COUNTER_API_SUCCESS: "SET_COUNTER_API_SUCCESS",
  SET_COUNTER_API_FAILURE: "SET_COUNTER_API_FAILURE",
}